Python-Final/AppCoder/App1/urls.py
from django.urls import path
from App1.views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    
    path("",inicio, name="Inicio"),
    path("login/",InicioSesion, name="Login"),
    path("logout/",LogoutView.as_view(template_name="App1/logout.html"), name="Logout"),
    path("registro/",registro, name="SignIn"),
    path("nvo_cliente/", nuevo_cliente, name="NuevoCliente"),
    path("cliente_formulario/",cliente_formulario, name="FormularioCliente"),
    path("reparacion_formulario/", reparacion, name="FormularioReparacion"),
    path("resultados_stock/", mostrar_resultados ,name="Resultados"),
    path("agregarAvatar/", agregarAvatar, name="Avatar"),
    
    #CRUD StockPropio
    
    path("leer_stockpropio/", leer_stockpropio, name="StockPropio"),
    path("crear_stockpropio/", crear_stockpropio, name="Crear_stockpropio"),
    path("eliminar_stockpropio/<modelopropio>", eliminar_stockpropio, name="Eliminar_stockpropio"),
    path("editar_stockpropio/<modelopropio>", editar_stockpropio, name="Editar_stockpropio"),

    #CRUD Reparaciones usando Class
    path("reparacion/list/", listaReparacion.as_view(), name="ReparacionLeer"),
    path("reparacion/<int:pk>", DetalleReparacion.as_view(), name="ReparacionDetalle"),
    path("reparacion/crear/", CrearReparacion.as_view(), name="ReparacionCrear"),
    path("reparacion/editar/<int:pk>", ActualizarReparacion.as_view(), name="ReparacionActualizar"),
    path("reparacion/borrar/<int:pk>", BorrarReparacion.as_view(), name="ReparacionEliminar"),
]

#Imagen Soyus

urlpatterns += staticfiles_urlpatterns()

Python-Final/AppCoder/TerceraPre_Entrega/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("App1/",include("App1.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Python-Final/AppCoder/App1/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User

class Cliente(models.Model):
    
    def __str__(self):
        
        return f"cliente: {self.nombre} {self.apellido}" 
    
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    email = models.EmailField(default="pedal@gmail.com")
    direccion = models.CharField(max_length=80)
    localidad = models.CharField(max_length=50)
    provincia = models.CharField(max_length=50)
    pais = models.CharField(max_length=50)
    
class StockPropio(models.Model):
    
    def __str__(self):
        
        return f"modelo: {self.modelo}---- unidades:{self.unidades}"
    
    modelo = models.CharField(max_length=50)
    efecto = models.CharField(max_length=50)
    unidades = models.CharField(max_length=20)
    descripcion = models.TextField()
    precio = models.CharField(max_length=20)
    
class Reparacion(models.Model):
    
    def __str__(self):
        return f"Pedal: {self.nombre}---- cliente:{self.cliente}"
        
    nombre = models.CharField(max_length=50) #Nombre del pedal
    efecto = models.CharField(max_length=50) #Tipo de Efecto
    fabricante = models.CharField(max_length=50)
    volts = models.CharField(max_length=20) #alimentacion
    made = models.CharField(max_length=50) #procedencia
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    falla = models.TextField(max_length=500,default="Falla")
    envio = models.CharField(max_length=60)
    fechapedido = models.DateTimeField(blank=False, null=True, auto_now_add=True)
   
class PedalClon(models.Model):
    clon_de = models.CharField(max_length=80)
    mods = models.TextField()
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    envio = models.BooleanField()
    descripcion = models.TextField(max_length=500,default="Descripcion del pedal")
    fechapedido = models.DateTimeField(null=True, auto_now_add=True)

class Avatar(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="avatares", null=True, blank=True)

#Para más adelante queda:
class VentaPropio(models.Model):
    modelo = models.ForeignKey(StockPropio, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    envio = models.BooleanField(default=True)
    fechapedido = models.DateTimeField(null=True, auto_now_add=True)      
      

Python-Final/AppCoder/App1/forms.py
from django import forms
from App1.forms import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from App1.models import Avatar

class Cliente_Formulario(forms.Form):
    
    nombre = forms.CharField()
    apellido = forms.CharField()
    email = forms.EmailField()
    direccion = forms.CharField()
    localidad = forms.CharField()
    provincia = forms.CharField()
    pais = forms.CharField()
    
#choice Envio
opcionesEnvio= (("1", "Si"),
        ("2", "No") )

class Reparacion_Formulario(forms.Form):
    modelo = forms.CharField()
    efecto = forms.CharField()
    fabricante = forms.CharField()
    volts = forms.CharField()
    origen = forms.CharField()
    falla = forms.CharField(widget=forms.Textarea(attrs={'rows':4, 'cols':50}))
    envio = forms.ChoiceField(choices=opcionesEnvio)
    
    
class StockPropio_Formulario(forms.Form):
    modelo = forms.CharField()
    efecto = forms.CharField()
    unidades = forms.CharField()
    descripcion = forms.CharField(widget=forms.Textarea(attrs={'rows':4, 'cols':50}))
    precio = forms.CharField()
    

class UsuarioRegistro(UserCreationForm):
    
    email = forms.EmailField()
    password1=forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2=forms.CharField(label="Repetir la Contraseña", widget=forms.PasswordInput)
    
    class Meta:
        
        model = User
        fields = ["username", "email","first_name","last_name","password1","password2"]

class AvatarFormulario(forms.ModelForm):
    
    class Meta:
        
        model = Avatar
        fields = ["imagen"]

Python-Final/AppCoder/App1/views.py
from django.shortcuts import render
from django.http import HttpResponse
import datetime, random 
from App1.models import *
from App1.forms import *
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView,DeleteView
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
#Vistas Registrar Cliente y Reparacion

def InicioSesion(request):
    
    if request.method == "POST":
        
        form = AuthenticationForm(request, data = request.POST)
        
        if form.is_valid():
            
            usuario = form.cleaned_data.get("username")
            contra = form.cleaned_data.get("password")
            
            user = authenticate(username= usuario, password=contra)
            
            if user:
                
                login(request, user)
                
                return render(request, "App1/inicio.html", {"mensaje": f"Bienvenido {user}"})
        
        else:
            
            return render(request, "App1/inicio.html", {"mensaje": "Datos incorrectos"})
    
    else:
        
        form = AuthenticationForm()
        
    return render(request, "App1/login.html", {"formulario": form})

def registro(request):
    
    if request.method == "POST":
        
        form = UsuarioRegistro(request.POST)
        
        if form.is_valid():
            
            username = form.cleaned_data["username"]
            form.save()
            return render(request,"App1/inicio.html", {"mensaje":"Usuario Creado"})

    else:
        
        form = UsuarioRegistro()
        
    return render(request, "App1/registro.html", {"formulario": form})
        
def inicio(request):
    
    return render(request, "App1/inicio.html")

def nuevo_cliente(request):
    
    client = Cliente(nombre = "Abel",apellido ="Leder", direccion = "Entre Rios 1191",localidad="Bella Vista",provincia="Buenos Aires",pais="Argentina")
    
    client.save()
    
    return render(request, "App1/nuevo_cliente.html")
    
def cliente_formulario(request):
    
    if request.method == "POST":
        
        formulario1 = Cliente_Formulario(request.POST)
        
        if formulario1.is_valid():
            
            info = formulario1.cleaned_data
            
            cliente = Cliente(nombre=info["nombre"],apellido=info["apellido"],email=info["email"],direccion=info["direccion"],localidad=info["localidad"],provincia=info["provincia"],pais=info["pais"])            
            
            cliente.save()
            return render(request,"App1/inicio.html")
    else:
    
        formulario1= Cliente_Formulario()
    
    return render(request,"App1/cliente_formulario.html",{"form1":formulario1})

def reparacion(request):
     
    if request.method == "POST":
        
        formula1 = Reparacion_Formulario(request.POST)
        
        if formula1.is_valid():
            
            info = formula1.cleaned_data
            
            reparacion = Reparacion(nombre=info["modelo"],efecto=info["efecto"],fabricante=info["fabricante"],volts=info["volts"],origen=info["origen"],cliente=info["cliente"],falla=info["falla"],envio=info["envio"],)            
            reparacion.save()
            return render(request,"App1/inicio.html")
    else:
    
         formula1= Reparacion_Formulario()
    
     
         return render (request,"App1/reparacion_formulario.html",{"form2":formula1})

#Imagenes

@login_required
def agregarAvatar(request):
    
    if request.method=="POST":
        
        form= AvatarFormulario(request.POST, request.FILES)
        
        if form.is_valid():
            
            usuarioLogin = User.objects.get(username=request.user)
            
            avatar = Avatar(usuario=usuarioLogin, imagen= form.cleaned_data["imagen"])
            
            avatar.save()
            
            return render(request, "App1/inicio.html")
        
    else:
            form = AvatarFormulario()
            
    return render(request,"App1/agregarAvatar.html",{"formulario":form})
            

# CRUD StockPropio

def leer_stockpropio(request):
    
    pedal = StockPropio.objects.all()
    
    contexto = {"modelopropio": pedal}
    
    return render (request,"App1/pedalespropios.html", contexto)

@login_required
def crear_stockpropio(request): 
    if request.method == "POST":
        
        formula1 = StockPropio_Formulario(request.POST)
        
        if formula1.is_valid():
            
            info = formula1.cleaned_data
            
            modelopropio = StockPropio(modelo=info["modelo"],efecto=info["efecto"],unidades=info["unidades"],descripcion=info["descripcion"],precio=info["precio"])            
            modelopropio.save()
            return render(request,"App1/inicio.html")
    else:
        
         formula1= StockPropio_Formulario()
    
     
         return render (request,"App1/nuevo_stock_propio.html",{"form1":formula1})
 
@login_required   
def eliminar_stockpropio(request,modelopropio):
    
    modelo= StockPropio.objects.get(modelo=modelopropio)
    modelo.delete()
    
    modelo=StockPropio.objects.all()
    contexto={"nombre":modelo}
    
    return render(request,"App1/pedalespropios.html",contexto)
 
@login_required   
def editar_stockpropio(request, modelopropio):
    
    pedalpropio= StockPropio.objects.get(modelo=modelopropio)
    
    if request.method == "POST":
        
        formula1 = StockPropio_Formulario(request.POST)
        
        if formula1.is_valid():
            
            info = formula1.cleaned_data
            
            pedalpropio.modelo= info["modelo"]
            pedalpropio.efecto= info["efecto"]
            pedalpropio.unidades= info["unidades"]
            pedalpropio.descripcion= info["descripcion"]
            pedalpropio.precio= info["precio"]
            pedalpropio.save()
            return render(request,"App1/inicio.html")
    else:
        
         formula1= StockPropio_Formulario(initial={"modelo":pedalpropio.modelo, "efecto":pedalpropio.efecto,
            "unidades":pedalpropio.unidades,"descricion":pedalpropio.descripcion,"precio":pedalpropio.precio})
    
     
         return render (request,"App1/editar_stock_propio.html",{"form1":formula1,"modelo": modelopropio})

# CRUD Reparaciones

class listaReparacion(LoginRequiredMixin, ListView):

    model = Reparacion
    

class DetalleReparacion(LoginRequiredMixin, DetailView):

    model = Reparacion
    
    
class CrearReparacion(LoginRequiredMixin, CreateView):

    model = Reparacion
    success_url = "/App1/reparacion/list"
    fields = ["nombre","efecto","fabricante","volts",
    "made","falla","envio",]

class ActualizarReparacion(LoginRequiredMixin, UpdateView):

    model = Reparacion
    success_url = "/App1/reparacion/list"
    fields = ["nombre","efecto","fabricante","volts",
    "made","falla","envio",]

class BorrarReparacion(LoginRequiredMixin, DeleteView):
    
    model = Reparacion
    success_url = "/App1/reparacion/list"
    


# Esto lo voy a borrar
def mostrar_resultados(request):
    
    if request.GET["modelo"]:
        
        modelo = request.GET["modelo"]
        
        modelos= StockPropio.objects.filter(modelo__icontains=modelo)
        unidades = StockPropio.objects.filter(modelo__icontains=modelo)
        
        return render (request, "App1/resultadostock.html",{"modelos":modelos ,"unidades":unidades})
    else:
        respuesta = "No enviaste datos."
    
    return HttpResponse(respuesta)

Python-Final/AppCoder/App1/templates/App1/cliente_formulario.html
{% extends "App1/padre.html" %}


{% load static %}

{% block titulo %}

SoY-uS : Dispositivos electrónicos para músicos

{% endblock %}

{%block texto%}

<form action="" method="POST"> {% csrf_token %}

    <table>

            {{form1.as_table}}

    </table>

        <input type="submit" value="Registrarse">
</form>

{% endblock %}

<!--<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <form action="" method="POST"> {% csrf_token %}

        <table>

                {{form1.as_table}}

        </table>

            <input type="submit" value="Registrarse">
    </form>

</body>
</html>

Python-Final/AppCoder/App1/templates/App1/editar_stock_propio.html

{% extends "App1/padre.html" %}

{% load static %}

{% block titulo %}

Agregar Nuevo Stock de Pedales Propios

{% endblock %}

{%block texto%}

<form action="" method="POST"> {% csrf_token %}

    <table>

            {{form1.as_table}}

    </table>
    <input type="submit" value="OK">
    
</form>
{% endblock %}

Python-Final/AppCoder/App1/templates/App1/login.html
{% extends "App1/padre.html" %}


{% load static %}

{% block titulo %}

SoY-uS : Dispositivos electrónicos para músicos
<br>
<hr style="height: 1%;">
Inicio de Sesión

{% endblock %}

{%block texto%}

<form action="" method="POST">{% csrf_token %}


    {{formulario.as_p}}

    <button type="submit"> Iniciar sesión</button>


</form>

{% endblock %}

Python-Final/AppCoder/App1/templates/App1/logout.html

{% extends "App1/padre.html" %}

{% load static %}

{% block titulo %}

¡Cerraste Sesión!

{% endblock %}

{%block texto%}

{% endblock %}

Python-Final/AppCoder/App1/templates/App1/nuevo_cliente.html
{% extends "App1/padre.html" %}


{% load static %}

{% block titulo %}

SoY-uS : PAGINA NUEVOS CLIENTES

{% endblock %}

Python-Final/AppCoder/App1/templates/App1/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="Abel Leder " />
        <title>SoYuS</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'App1/assets/favicon.ico' %}"/>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'App1/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-bottom">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="https://www.instagram.com/soyus_ar/">SoYuS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active"><a class="nav-link" href="{% url 'Inicio' %}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'FormularioReparacion' %}">Reparaciones</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'StockPropio' %}">Modelos Propios</a></li>
                        {% if request.user.is_authenticated%}
                        
                        <p style="color: aliceblue;"> Hola {{user.username}}  </p>

                        {% with user.avatar_set.first  as miAvatar %}
                        
                        {% if miAvatar %}
                        
                        <img src="{{miAvatar.imagen.url}}" alt="sin imagen" style="max-width: 50px;">
                        
                        {% endif %}
                        
                        {% endwith %}        

                        <li class="nav-item"><a class="nav-link" href="{% url 'FormularioCliente' %}">Crear Cliente</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Logout' %}">Cerrar Sesión</a></li>
                        
                        {% else %}
                        
                        <li class="nav-item"><a class="nav-link" href="{% url 'SignIn' %}"> Registrarse</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Login' %}">Iniciar Sesión</a></li>     
                        
                        {% endif %}    
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Content-->
        <section>
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-lg-6">
                        <h1 class="mt-5" style=color:blue>

                            {% block titulo %}

                            {% endblock %}

                        </h1>
                        <p style="color: darkblue;">
                            {% block texto%}

                            

                            {% endblock %}

                                                    
                        </p>
                    
                    </div>
                </div>
            </div>
        </section>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'App1/js/scripts.js' %}"></script>
    </body>
</html>

Python-Final/AppCoder/App1/templates/App1/pedalespropios.html
{% extends "App1/padre.html" %}


{% load static %}

{% block titulo %}
<p style="text-align: center;"> Estos son los modelos que tenemos en Stock Actualmente </p> 
    
    {% endblock %}

{%block texto%}

<br>

{% if request.user.is_superuser %}
<a href="{% url 'Crear_stockpropio' %}" style="position:absolute"> Crear Stock</a> 
{% endif %}   

{% for pedal in modelopropio %}

    <p style="color:darkred; text-align: center; font-size:200%"> Modelo: {{pedal.modelo}} </p> 
    <hr>
    <p style="color: blue; text-align: center; font-size:150%; "> Efecto:  {{pedal.efecto}} </p> 
    <hr>
    <p style="text-align: justify; font-weight:bold;" > Reseña: {{pedal.descripcion}}</p> 
    <hr>
    <p>Precio: {{pedal.precio}}</p> 
    <hr>
    <p> En Stock: {{pedal.unidades}}</p> 

    {% if request.user.is_superuser %}
        <button>

        <a href="{% url 'Eliminar_stockpropio' pedal.modelo %}"> Eliminar Stock</a>
                                                             
        </button>
    
        <button>
        <a href="{% url 'Editar_stockpropio' pedal.modelo %}"> Editar Stock</a>
        </button>
    {% else %}

    {% endif %}
    <button>

                                                                           
{% endfor %}



{% endblock %}


Python-Final/AppCoder/App1/templates/App1/reparacion.html
{% extends "App1/padre.html" %}

{% load static %}

{% block titulo %}

PEDIDO DE REPARACIONES

{% endblock %}

Python-Final/AppCoder/App1/templates/App1/reparacion_confirm_delete.html
{% extends "App1/padre.html" %}


{% load static %}

{% block titulo %}

Eliminar Reparación

{% endblock %}

{%block texto%}

<form action="" method= "POST"> {% csrf_token %}


   <p>¿Seguro que vas a borrar la reparación?</p>

    <button type="submit"> Borrar </button>
    <button><a href="{% url 'ReparacionLeer' %}"> Regresar </a></button> 


</form>

{% endblock %}

Python-Final/AppCoder/App1/templates/App1/reparacion_detail.html
{% extends "App1/padre.html" %}


{% load static %}

{% block titulo %}

<p style="text-align: center;">  Reparacion para hacer: </p>
    
{% endblock %}

{%block texto%}

<p> Nombre: {{reparacion.nombre}}</p>
<hr>
<p> Efecto:  {{reparacion.efecto}} </p>
<hr>
<p> volts: {{reparacion.volts}}</p>  
<hr>
<p>Made: {{reparacion.made}}</p>
<hr>
<p>Falla: {{reparacion.falla}}</p>
<hr>
<p>Envio: {{reparacion.envio}}</p>
<hr>
<p>Fecha de ingreso: {{reparacion.fechapedido}}</p>

<a href="{% url 'ReparacionLeer' %}"> Regresar </a>


{% endblock %}

Python-Final/AppCoder/App1/templates/App1/reparacion_form.html
{% extends "App1/padre.html" %}


{% load static %}

{% block titulo %}

Nueva Reparación

{% endblock %}

{%block texto%}

<form action="" method= "POST"> {% csrf_token %}


    {{form.as_p}}

    <input type="submit" name="Enviar">
    <button><a href="{% url 'ReparacionLeer' %}"> Regresar </a></button> 


</form>

{% endblock %}

Python-Final/AppCoder/App1/templates/App1/reparacion_formulario.html
{% extends "App1/padre.html" %}


{% load static %}

{% block titulo %}

Ingrese su reparación y nos contactaremos

{% endblock %}

{%block texto%}

<form action="" method="POST"> {% csrf_token %}

    <table>

            {{form2.as_table}}

    </table>

{% endblock %}

Python-Final/AppCoder/App1/templates/App1/reparacion_list.html
{% extends "App1/padre.html" %}


{% load static %}

{% block titulo %}
<p style="text-align: center;"> Lista de Reparaciones </p>
    
{% endblock %}

{%block texto%}

<a href="{% url 'ReparacionCrear' %}" > Nueva Reparacion </a>
    
{% for reparacion in object_list %}

    
    <p> {{reparacion.cliente}}  
    <hr>
     Modelo: {{ reparacion.nombre }} 
    <hr>
    Fecha de pedido: {{reparacion.fechapedido}}      
    <br><br>
    <li>
    <a href="{% url 'ReparacionDetalle' reparacion.id %}" > Ver Reparacion </a>
    <a href="{% url 'ReparacionActualizar' reparacion.id %}"> Editar Reparacion </a>
    <a href="{% url 'ReparacionEliminar' reparacion.id %}"> Eliminar Reparacion</a></li>
    <br>
    <hr style="height: 1%;">
    <br>
    </p> 

{% endfor %}


{% endblock %}

Python-Final/AppCoder/App1/templates/App1/resultadostock.html
{% extends "App1/padre.html" %}


{% load static %}

{% block titulo %}

<p>En la busqueda de: {{modelo}} </p>

{% for modelo in modelos %}

    <p>Del modelo {{modelo.modelo}}</p>
    <p>Unidades en Stock: {{modelo.unidades}}</p>

{% endfor %} 


{% endblock %}